#!/usr/bin/env bash
# Configure your nginx server so that /redirect_me is redirecting to another path

set -e 

apt update
apt install -y nginx
sudo ufw allow 'Nginx Full'
sudo ufw  --force enable
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sed -i '/server_name_;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
