#!/usr/bin/env bash
# script thaat debugs nginx

sudo apt-get update
sudo apt-get install -y nginx

set -e

sudo bash -c 'cat > /etc/nginx/sites-available/default << EOF

server {
    listen 80 default_server;
    listen[::]:80 default_server;

    root /var/html;
    index index.html index.htm index.nginx-debian.html;

    server_name_;

    location / {
    	try_files \$uri \$uri/ =404;
    }
}
EOF'

sudo nginx -t 
sudo service nginx reload
