#!/usr/bin/env bash
# script that debugs nginx

apt-get update 
apt-get install -y nginx
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx start
