#!/usr/bin/env bash
#script that prints a string to infinity 

handle_sigterm()
{
   echo "I am invincible!!!"
   exit 0

}

trap 'handle_sigterm' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
    
done
