#!/usr/bin/env bash
#script prints "Best school" 10 times except for 9.

count=0

while [[ $count -lt 10 ]]; do
	echo "Best School"

if [[ $count -eq  8 ]]; then
	echo "Hi"

fi
	count=$((count + 1))
done
