#!/usr/bin/env bash
#script prints 1 - 20 with strings printed at specific indexes.

i=1

while [[ $i -le 20 ]]; do

	case $i in

	     4) echo "bad luck from China"
		;;

	     9) echo "bad luck from Japan"
		;;

	    17) echo "bad luck from Italy "
		;;

	    *)echo $i

       esac

   i=$((i + 1))

done

