#!/usr/bin/env bash
# Write a Bash script that configures the container to fit the above requirements

apt-get update
apt-get install -y nginx

sudo sed -i 's/^user .*;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/80/ 8080/g' /etc/nginx/sites-available/default

nginx -t
service nginx restart
